'use strict';

/**
 * @ngdoc service
 * @name docubasic3App.apiUrl
 * @description
 * # apiUrl
 * Service in the docubasic3App.
 */
angular.module('docubasic3App').constant('apiUrl', function () {
	var BASE_URL = 'api/v1/',
       	apiRoot = $('#apiRoot').attr('href') ? $('#apiRoot').attr('href') : '';

   	BASE_URL = apiRoot + BASE_URL;
	
return {
      'orgname': BASE_URL + 'autocode',
  	'signup':BASE_URL + 'register',
  	'tcode':BASE_URL + 'chkcode',
      'tcodecheck':BASE_URL + 'autocodeexist',
      'admin':BASE_URL + 'auth',
      'nation':BASE_URL + 'countries',
      'states':BASE_URL + 'currencies',
      'tasks':BASE_URL + 'displayCategory',
      'companyinfo':BASE_URL + 'companyinfo',
      'setaddress':BASE_URL + 'companyaddress',
      'logo':BASE_URL + 'companylogo',
      'changecurrancy':BASE_URL + 'companycurrency',
      'addtask':BASE_URL + 'taskCategory',
      'showprice':BASE_URL + 'allpriceblock',
      'showvendors':BASE_URL + 'allvendors',
      'addprice':BASE_URL + 'priceblocks',
      'password':BASE_URL + 'passwordauth',
      'resource':BASE_URL + 'allresources',
      'addresource':BASE_URL + 'resources',
      'rememberpassword':BASE_URL + 'forget',
      'vendorsadd':BASE_URL + 'vendors',
      'client':BASE_URL + 'customers',
      'clientget':BASE_URL + 'allcustomers',
      'projecttask':BASE_URL + 'allTask',
      'projecttaskpost':BASE_URL + 'projectTask',
      'getdiscontdata':BASE_URL + 'alldiscountblock',
      'postdiscontdata':BASE_URL + 'discountblocks',
      'gettaxdata':BASE_URL + 'alltaxblock',
      'posttaxdata':BASE_URL +'taxblocks',
      'postnotedata':BASE_URL +'notes',
      'getnotedata':BASE_URL +'allnote',
      'userdata':BASE_URL +'users/all/:id',
      'billingdata':BASE_URL +'billing/:id',
      'packagedata':BASE_URL +'packages',
      'userdatapost':BASE_URL +'users',
      'getodosdata':BASE_URL +'alltodos',
      'addtodosdata':BASE_URL +'todos',
      'admindata':BASE_URL +'accountadmin',
      'changeadmin':BASE_URL +'companyadmin',
      'praposalcountdata':BASE_URL +'proposal/:id',
      'validuser':BASE_URL +'chkemail',
      'resentactivitydata':BASE_URL +'recentproposals',
      'searchanalys':BASE_URL +'analyticSearch',
      'packageupgrade':BASE_URL +'process',
      'searchquery':BASE_URL +'dashboardSearch',
      'collabdatapost':BASE_URL +'showUsers',
      'resourceprice':BASE_URL +'resources/:id',
      'getchart':BASE_URL +'proposal_graph',
      'getchartloss':BASE_URL +'proposal_loss_graph',
      'getchartown':BASE_URL +'proposal_won_graph',
      'packageadd':BASE_URL +'packages',
      'alltenancy':BASE_URL +'showTenancy',
      'disscountadd':BASE_URL +'discounts',
      'discountedtenancys':BASE_URL +'discounts',
      'costinhouse':BASE_URL +'inhouseCost',
      'usersall':BASE_URL +'allusers',
      'userlogo':BASE_URL +'updatelogo',
      'singleuser':BASE_URL +'users/:id',
      'profileupdate':BASE_URL +'updateProfile',
      'versionchange':BASE_URL +'insert_version/:id/:tid',
      'pagesort':BASE_URL +'page_sorting',
      'billinggraph':BASE_URL +'billing_graph_day',
      'getallcomments':BASE_URL +'allcomments',
      'addcomments':BASE_URL +'comments',
      'deletecomment':BASE_URL +'comments/:id',
      'commentedit':BASE_URL +'comments/:id',
      'canvassave':BASE_URL +'saveNewContent',
            

      //update service//
      'updatepricedata':BASE_URL +'priceblocks/:id',
      'priceblockupdate':BASE_URL +'priceblocks/:id',
      'updatevendordata':BASE_URL +'vendors/:id',
      'updateproject':BASE_URL +'updateProject',
      'updateclientdata':BASE_URL +'customers/:id',
      'updateresourcedata':BASE_URL +'resources/:id',
      'updatetaskdata':BASE_URL +'updateCategory',
      'updatediscountdata':BASE_URL +'discountblocks/:id',
      'updatetaxdata':BASE_URL +'taxblocks/:id',
      'updatenotedata':BASE_URL +'notes/:id',
      'completetask':BASE_URL +'todos/complete/:id',
      'userupdate':BASE_URL +'users/:id',
      'userdelete':BASE_URL +'users/:id',
      'completealltask':BASE_URL +'todos/complete/:id',
      'opentask':BASE_URL +'todos/active/:id',
      'uptask':BASE_URL +'todos/:id',
      'searchbilling':BASE_URL +'billing_history',
      'packageupdate':BASE_URL +'packages/:id',
      'discountupdate':BASE_URL +'discounts/:id',

      //delete service//
      'removetask':BASE_URL +'deleteCategory',
      'removeproject':BASE_URL +'deleteProject',
      'removenote':BASE_URL +'deletent',
      'deleteresourcedata':BASE_URL +'resources/:id',
      'deletevendordata':BASE_URL +'vendors/:id',
      'deleteclientdata':BASE_URL +'customers/:id',
      'deletepricedata':BASE_URL +'priceblocks/:id',
      'deletediscountdata':BASE_URL +'discountblocks/:id',
      'deletetaxdata':BASE_URL +'taxblocks/:id',
      'stylecontent':BASE_URL +'style/details/:id',
      'packagedelete':BASE_URL +'packages/:id',
      'discountdelete':BASE_URL +'discounts/:id',

      'sendpagedata':BASE_URL +'pages',
      'getpage':BASE_URL +'allpages',
      'getstyles':BASE_URL +'allstyles',
      'sendstyledata':BASE_URL +'style',
      'updatestyle':BASE_URL +'style/:id',
      //'sendpagedata':BASE_URL +'pages',
      //'getpage':BASE_URL +'allpages',
      'pageupdate':BASE_URL +'pages/:id',
      'sendtempdata':BASE_URL +'templates',
      'tempdata':BASE_URL +'alltemplates',
      'tempdataupdate':BASE_URL +'editTemplates',
      'praposalcreate':BASE_URL +'createProposal',
      'pagelist':BASE_URL +'selectedTemplates',
      'pagesave':BASE_URL +'saveContent',
      'getpraposales':BASE_URL +'allproposals',
      'downloadpage':BASE_URL +'downloadProposalpdf',
      'praposaldelete':BASE_URL +'deleteProposal',
      'mailsend':BASE_URL +'sendProposal',
      'changepname':BASE_URL +'editProposalname/:id',
      'getcollab':BASE_URL +'allCollaborators',
      'clone':BASE_URL +'proposal_details',
      'getreadaccess':BASE_URL +'inviteCollaborators',
      'praposalwondata':BASE_URL +'won/:id',
      'praposallossdata':BASE_URL +'loss/:id',
      'reviewproposal':BASE_URL +'customerReview',
      'rejectproposal':BASE_URL +'rejectProposal',
      'signupload':BASE_URL +'uploadSignature',
      'approvepraposal':BASE_URL +'approveProposal',
      'getiamgesdata':BASE_URL +'images',
      'imageup':BASE_URL +'upload',
      'pagecontent':BASE_URL +'pagecontent',
      'proposaltask':BASE_URL +'alldata',
      'profitanalysys':BASE_URL +'costProfitview',
      'cstprofit':BASE_URL +'dashboardcostprofit',
      'costprofitgraph':BASE_URL +'costprofit_graph_day',
   	};
}());